### ISSUE TITLE
How to creates a new octree by a `octomap_msgs/Octomap` message

### ISSUE THREAD

**Issue by punnpkin** [OctoMap/octomap_msgs#12]
Hello there,

I'm trying an example of conversing `octomap_msgs/Octomap` message into a oct tree.

The callback function which I wrote is:

```
void callback(const octomap_msgs::Octomap &msg)
{
    octomap::AbstractOcTree* tree = octomap_msgs::fullMsgToMap(msg);
}
```

But an error occurred at compile time:

```
In function `octomap_msgs::fullMsgToMap(octomap_msgs::Octomap_<std::allocator<void> > const&)': 
octo_move.cpp:(.text+0x14e): undefined reference to octomap::AbstractOcTree::createTree(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, double)'
```

What I want to ask is, am I right in writing like this? How can I solve this problem?

Thanks a lot

**Comment by wxmerkt** [comment]
Hi @punnpkin,
Can you include your `CMakeLists.txt` entries for the source file? It appears that maybe you are missing to link to octomap library.

Best wishes

**Comment by punnpkin** [comment]
> Hi @punnpkin,
> Can you include your `CMakeLists.txt` entries for the source file? It appears that maybe you are missing to link to octomap library.
> 
> Best wishes

yes... I am missing to link octomap_ros lib, thank you
