### ISSUE TITLE
Release for ROS 2 Foxy

### ISSUE THREAD

**Issue by henningkayser** [OctoMap/octomap_msgs#16]
@wxmerkt I saw that you just ran a Foxy release for octomap which is great! Could you also make a release for `octomap_msgs`? We're depending on it for the [MoveIt 2 Foxy](https://github.com/ros-planning/moveit2/issues/190).

**Comment by wxmerkt** [comment]
Hi @henningkayser,
Happy to make a release. At the moment, the `ros2` branch is at version 0.3.3. The ROS1 version (`melodic-devel`) is at 0.3.5. We cannot directly run bloom with this version clash. How would it be best to proceed:

1) Increase the version number in the `ros2` branch, say to `1.x` or `2.x`.
2) Leave the version number but use tags that are prefixed with `ros2_`, i.e. `ros2_0.3.3`. In this case bloom can look for the correct tags. It may still cause issues in the release repository (as now two tags `upstream/0.3.3` will exist).

Looking forward to input on best practices!

Thanks,
Wolfgang

**Comment by henningkayser** [comment]
Thanks for the quick response!
In this case the easiest way would be option 1, bump to `2.x` and iterate from there (it's unlikely to ever conflict with a future ROS1 version, right?). We also debated using prefixed tags but decided against it because of the reason you mentioned.

**Comment by wxmerkt** [comment]
Thanks for the input! I've made the release request: https://github.com/ros/rosdistro/pull/25642
Please let me know if there's anything else missing.

**Comment by henningkayser** [comment]
Awesome, thanks @wxmerkt!
