### ISSUE TITLE
Use conversion.h in python

### ISSUE THREAD

**Issue by tadteo** [OctoMap/octomap_msgs#17]
I was trying to use octomap_msgs conversions.h in python but I did not find anything that explains how to do that. Is it possible for example use the function msgToMap() in python? If yes how? Otherwise, there is a way to implement it in python?

**Comment by wxmerkt** [comment]
Hi @TadielloM,
There is no official Python wrapper for the conversions or OctoMap at this stage. If you want to build one, you can either write it directly as a Python library or using e.g. Pybind11 or boost-python. Note, passing serialised ROS messages between C++ and Python is not trivial.

**Comment by MakerFace** [comment]
when I import my module in python, it print ' Import Error: path/to/octomap_gen.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK8octomath6Pose6D3invEv', how can I resolve this fatal error? think you.

**Comment by wxmerkt** [comment]
Hi @MakerFace - I am not sure which wrapper you are using. However, the above message is clearly a link error. Make sure that you are linking against `octomath`.
