### ISSUE TITLE
rolling release

### ISSUE THREAD

**Issue by wep21** [OctoMap/octomap_msgs#19]
Will this package be released in `rolling`?

**Comment by wxmerkt** [comment]
Releases into `rolling` should happen automatically from `foxy` I thought? `octomap_msgs` is released to foxy (https://github.com/ros/rosdistro/blob/a5f75c7667d603f643e87f72d5d5f8bbbf36dfb1/foxy/distribution.yaml#L2136). Otherwise I am happy to make a release...

**Comment by wep21** [comment]
I guess you should add `octomap_msgs` in `rolling` as well with `bloom` like below.
https://github.com/ros/rosdistro/pull/29192

**Comment by wxmerkt** [comment]
I just made the release cf. https://github.com/ros/rosdistro/pull/29197
