### ISSUE TITLE
Foxy version

### ISSUE THREAD

**Issue by tylerjw** [OctoMap/octomap_msgs#21]
As @Ace314159 stated here: https://github.com/OctoMap/octomap_msgs/pull/20#issuecomment-1231096995

The change I made to make this package work in Rolling does not work on Foxy. Is there a chance we could create a foxy branch without this change?

**Comment by wxmerkt** [comment]
Is there a reason why this change was required in newer versions of ROS2 but would break in older versions? Was this something captured in a changelog/migration guide for message packages?

Happy to create a foxy branch if that is the only solution to resolve it

**Comment by tylerjw** [comment]
The change for Rolling/Galactic/Humble is caused by the changes in ROS 2 around include directory ordering for underlays.

**Comment by wxmerkt** [comment]
Thank you - I created a foxy branch without the change in #20. Do we need a binary release to any of the distros with your change in #20 or does it only affect building from source?

**Comment by tylerjw** [comment]
@Ace314159 do you mind testing this to confirm if this fixes the problem you experienced?

**Comment by Ace314159** [comment]
@tylerjw Yeah I have already started a Windows build on https://github.com/Ace314159/ros2-foxy-windows-packages/runs/8098828859, and it looks like it has succeeded! Thank you!

**Comment by wxmerkt** [comment]
Great, thank you for the confirmation!
