### ISSUE TITLE
Release into ROS Melodic

### ISSUE THREAD

**Issue by 130s** [OctoMap/octomap_msgs#9]
This package is [depended by some MoveIt! packages](http://repositories.ros.org/status_page/blocked_releases_melodic.html?q=id%3D%22octomap_msgs%22&s=6&r=1).

Thanks!

**Comment by ahornung** [comment]
I just released the latest version, should appear soon.

**Comment by 130s** [comment]
I saw https://github.com/ros/rosdistro/pull/17320. Thanks for the prompt(est) reaction.
